### ISSUE TITLE
DARK theme

### ISSUE THREAD

**Issue by menjilx** [biati-digital/nova-advanced-new-file#1]
Is there any option to make Nova ANF extension "dark" on a "dark theme"? 
![image](https://user-images.githubusercontent.com/14908836/98077332-02ca8600-1eab-11eb-8a86-71e33e7fb29b.png)
Cause right now it won't update or follow the currently active theme.

Thank you!

**Comment by biati-digital** [comment]
The extension does not control that, your theme should handle that, checkout the gif in the readme and you'll see that i use dark mode with a dark theme and the advanced new file it's displayed using the correct theme.

So probably the theme you are using does not define that the dark mode should be used.

**Comment by menjilx** [comment]
> The extension does not control that, your theme should handle that, checkout the gif in the readme and you'll see that i use dark mode with a dark theme and the advanced new file it's displayed using the correct theme.
> 
> So probably the theme you are using does not define that the dark mode should be used.

I got it working now. :) Thanks!

**Comment by biati-digital** [comment]
Glad it's working 😊
