### ISSUE TITLE
Subfolders are not in the list

### ISSUE THREAD

**Issue by pelemarse** [biati-digital/nova-advanced-new-file#2]
Nova App 5.1 Build 257074 Released on 2021.03.22
Advanced New File Extension version: 1.0.3

<img width="1094" alt="Screenshot 2021-04-03 at 00 39 29" src="https://user-images.githubusercontent.com/29234307/113456528-1b1cdd80-9416-11eb-8832-3bb81b0f072a.png">

**Comment by biati-digital** [comment]
i'm not able to replicate, does this happen with all projects? do you have ignored folders in the extension preferences?

**Comment by pelemarse** [comment]
> i'm not able to replicate, does this happen with all projects? do you have ignored folders in the extension preferences?

1) Does this happen with all projects? Yes.
2) Do you have ignored folders in the extension preferences? No. Only what was by default.

I found that when I add 'console.log (list)' above the code line 'resolve (list)' in the function listWorkspaceFolders, everything works normally.

<img width="1112" alt="Screenshot 2021-04-04 at 23 20 47" src="https://user-images.githubusercontent.com/29234307/113520753-0ff4b980-959e-11eb-892d-1313f1b1e854.png">

**Comment by biati-digital** [comment]
Not sure how adding a console log could fix any potential error, there must be something else happening, difficult to know as i can't replicate it.

I'll make some tests to see if I'm able to find out what's happening.

**Comment by biati-digital** [comment]
I've submitted an update 1.0.4, this update should display the folders list faster and more reliable, also a lot more info has been added in the logs to be able to find errors faster, from the extension preferences you can enable the option **Show Logs** if required.

Please update the extension and try it and let me know if you are able to see the subfolders.

**Comment by pelemarse** [comment]
Now Everything is working fine.

**Comment by biati-digital** [comment]
Awesome.
